"""
Test configuration and fixtures
Generated by Testing Agent: 2025-08-18T21:47:23.452500
"""

import pytest
import sys
from pathlib import Path

# Add project root to Python path
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))


@pytest.fixture
def workspace_path():
    """Provide workspace path for tests."""
    return Path.cwd()


@pytest.fixture
def test_task_system():
    """Provide a test instance of CompleteTaskExecutionSystem."""
    from complete_task_execution_system import CompleteTaskExecutionSystem
    return CompleteTaskExecutionSystem()


@pytest.fixture
def sample_task_data():
    """Provide sample task data for testing."""
    return {
        "task_description": "Test Task",
        "requirements": "Test requirements for validation",
        "agent_types": ["documentation", "worker", "testing"]
    }
